version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - noctx
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
  settings:
    revive:
      rules:
        - name: var-naming
        - name: receiver-naming
        - name: error-strings
        - name: error-naming
        - name: context-as-argument
        - name: context-keys-type

formatters:
  enable:
    - gofmt
    - goimports
